baseUrl = "https://umool.com/"
languageCode = "ko-kr"

title = "초하 (草河)"
theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "choha"
googleAnalytics = "UA-142276080-1"
enableRobotsTXT = true

# summarylength = 0
paginate = 15

pluralizelisttitles = false

FootnoteReturnLinkContents = "↩"

## Site Settings
[params]
    author = "choha"
    title = "Choha"
    description = ""
    authorimage = "/img/avatar_frame.png"
    #dateformat = "Mon, Jan 2, 2006"
    dateformat = "2006"

    # sidebar, copyright & license
    copyright = "choha"
    #license = "CC BY-SA 4.0"
    #licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    # showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "agate"
    highlightjslanguages = ["go"]

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

# taxonomies
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"



## Social Accounts
[params.social]
    #github = "devplayg"
    #instagram = "<username>"
    #xing = "<username>"
    #linkedin = "<username>"
    #twitter = "devplayg"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    email = "umoolchoha@gmail.com"
    #gravatar = "your-email@example.com"

[menu]
    [[menu.main]]
        identifier = "poet_2019"
        name = "2019年 作"
        weight = 10
        url = "/categories/2019%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2018"
        name = "2018年 作"
        weight = 11
        url = "/categories/2018%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2017"
        name = "2017年 作"
        weight = 12
        url = "/categories/2017%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2016"
        name = "2016年 作"
        weight = 13
        url = "/categories/2016%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2015"
        name = "2015年 作"
        weight = 14
        url = "/categories/2015%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2014"
        name = "2014年 作"
        weight = 15
        url = "/categories/2014%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2013"
        name = "2013年 作"
        weight = 16
        url = "/categories/2013%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_2012"
        name = "2012年 作"
        weight = 17
        url = "/categories/2012%E5%B9%B4-%E4%BD%9C/"
    [[menu.main]]
        identifier = "poet_paper"
        name = "논문"
        weight = 21
        url = "/categories/%EB%85%BC%EB%AC%B8/"
    [[menu.main]]
        identifier = "poet_essay"
        name = "수필"
        weight = 22
        url = "/categories/%EC%88%98%ED%95%84/"